name: build nginx

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: install requirement
        run: |
          sudo apt-get update
          sudo apt-get install autoconf autopoint libtool pkg-config g++ zlib1g-dev ca-certificates unzip
      - name: openssl
        run: |
          wget https://www.openssl.org/source/openssl-1.1.1h.tar.gz
          tar zxvf openssl-1.1.1h.tar.gz
      - name: pcre
        run: |
          wget https://ftp.pcre.org/pub/pcre/pcre-8.44.zip
          unzip pcre-8.44.zip
      - name: nginx
        run: |
          wget http://nginx.org/download/nginx-1.18.0.tar.gz
          tar zxvf nginx-1.18.0.tar.gz 
      - name: build-install
        run: |
          cd nginx-1.18.0
          ./configure --with-threads --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-stream --with-stream_ssl_module --with-stream_realip_module --with-stream_geoip_module --with-stream_ssl_preread_module --with-pcre=../pcre-8.44/ --with-openssl=../openssl-1.1.1h
          sudo make
          ls
      - name: Upload a Build Artifact 
        uses: actions/upload-artifact@v2.2.0
        with:
          path: nginx-1.18.0
